'use client';
import { useMemo, useState } from 'react';

type Meeting={id:number,title:string,date:string,time:string,location:string,chair:string,status:'Draft'|'Selesai',agenda:string,minutes:string};
const seed:Meeting[]=[
{id:1,title:'Mesyuarat Pengurusan Perpustakaan Bil. 3/2026',date:'2026-08-12',time:'09:00',location:'Bilik Mesyuarat Utama',chair:'Mohd Hikmal',status:'Selesai',agenda:'Prestasi perpustakaan, pinjaman buku dan program literasi',minutes:'Semua agenda dibincangkan. Program literasi diteruskan pada bulan September.'},
{id:2,title:'Mesyuarat Jawatankuasa ICT',date:'2026-08-18',time:'14:30',location:'Makmal ICT',chair:'Nur Aina',status:'Draft',agenda:'Penyelenggaraan PC dan penggunaan ICT',minutes:''},
];

export default function Home(){
 const [meetings,setMeetings]=useState(seed); const [active,setActive]=useState('dashboard'); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Meeting|null>(null); const [query,setQuery]=useState('');
 const filtered=useMemo(()=>meetings.filter(m=>(m.title+m.location+m.chair).toLowerCase().includes(query.toLowerCase())),[meetings,query]);
 const today=new Date().toISOString().slice(0,10);
 function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const item:Meeting={id:editing?.id??Date.now(),title:String(f.get('title')),date:String(f.get('date')),time:String(f.get('time')),location:String(f.get('location')),chair:String(f.get('chair')),status:String(f.get('status')) as Meeting['status'],agenda:String(f.get('agenda')),minutes:String(f.get('minutes'))};setMeetings(x=>editing?x.map(m=>m.id===editing.id?item:m):[item,...x]);setOpen(false);setEditing(null)}
 function exportText(m:Meeting){const text=`MINIT MESYUARAT\n\n${m.title}\nTarikh: ${m.date} | Masa: ${m.time}\nTempat: ${m.location}\nPengerusi: ${m.chair}\n\nAGENDA\n${m.agenda}\n\nMINIT / KEPUTUSAN\n${m.minutes||'Belum direkod.'}`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download=`minit-${m.date}.txt`;a.click()}
 return <div className="shell"><aside className="sidebar"><div className="brand">Meeting<span>Minute</span></div><nav className="nav">{[['dashboard','📊 Dashboard'],['meetings','📅 Mesyuarat'],['minutes','📝 Minit & Keputusan'],['reports','📈 Laporan']].map(([id,label])=><button key={id} className={active===id?'active':''} onClick={()=>setActive(id)}>{label}</button>)}</nav></aside><main className="main">
 <header className="top"><div><h1>{active==='dashboard'?'Dashboard Mesyuarat':active==='meetings'?'Senarai Mesyuarat':active==='minutes'?'Minit & Keputusan':'Laporan'}</h1><div className="muted">Urus mesyuarat, agenda, keputusan dan tindakan susulan.</div></div><button className="btn" onClick={()=>{setEditing(null);setOpen(true)}}>＋ Mesyuarat Baharu</button></header>
 {active==='dashboard'&&<><div className="grid"><div className="card"><div className="muted">Jumlah Mesyuarat</div><div className="stat">{meetings.length}</div></div><div className="card"><div className="muted">Akan Datang</div><div className="stat">{meetings.filter(m=>m.date>=today).length}</div></div><div className="card"><div className="muted">Selesai</div><div className="stat">{meetings.filter(m=>m.status==='Selesai').length}</div></div><div className="card"><div className="muted">Draft</div><div className="stat">{meetings.filter(m=>m.status==='Draft').length}</div></div></div><section className="section card"><h2>Mesyuarat Terkini</h2><MeetingTable data={meetings.slice(0,5)} onEdit={m=>{setEditing(m);setOpen(true)}} onExport={exportText}/></section></>}
 {active==='meetings'&&<section className="card"><div style={{display:'flex',gap:10,marginBottom:16}}><input placeholder="Cari mesyuarat..." value={query} onChange={e=>setQuery(e.target.value)} style={{flex:1,padding:11,border:'1px solid #cbd5e1',borderRadius:9}}/></div><MeetingTable data={filtered} onEdit={m=>{setEditing(m);setOpen(true)}} onExport={exportText}/></section>}
 {active==='minutes'&&<section className="card"><h2>Rekod Minit & Keputusan</h2><MeetingTable data={meetings} onEdit={m=>{setEditing(m);setOpen(true)}} onExport={exportText}/></section>}
 {active==='reports'&&<section className="grid"><div className="card"><div className="muted">Kadar selesai</div><div className="stat">{meetings.length?Math.round(meetings.filter(m=>m.status==='Selesai').length/meetings.length*100):0}%</div></div><div className="card"><div className="muted">Lokasi digunakan</div><div className="stat">{new Set(meetings.map(m=>m.location)).size}</div></div></section>}
 </main>{open&&<div className="modal"><div className="dialog"><h2>{editing?'Edit Mesyuarat':'Mesyuarat Baharu'}</h2><form className="form" onSubmit={save}><label>Tajuk<input name="title" required defaultValue={editing?.title}/></label><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><label>Tarikh<input type="date" name="date" required defaultValue={editing?.date}/></label><label>Masa<input type="time" name="time" required defaultValue={editing?.time}/></label></div><label>Tempat<input name="location" required defaultValue={editing?.location}/></label><label>Pengerusi<input name="chair" required defaultValue={editing?.chair}/></label><label>Status<select name="status" defaultValue={editing?.status||'Draft'}><option>Draft</option><option>Selesai</option></select></label><label>Agenda<textarea name="agenda" defaultValue={editing?.agenda}/></label><label>Minit / Keputusan<textarea name="minutes" defaultValue={editing?.minutes}/></label><div className="actions"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Batal</button><button className="btn">Simpan Mesyuarat</button></div></form></div></div>}</div>
}
function MeetingTable({data,onEdit,onExport}:{data:Meeting[],onEdit:(m:Meeting)=>void,onExport:(m:Meeting)=>void}){return <div className="table-wrap"><table className="table"><thead><tr><th>Mesyuarat</th><th>Tarikh</th><th>Tempat</th><th>Pengerusi</th><th>Status</th><th>Tindakan</th></tr></thead><tbody>{data.map(m=><tr key={m.id}><td><b>{m.title}</b><br/><span className="muted">{m.agenda.slice(0,70)}</span></td><td>{m.date}<br/>{m.time}</td><td>{m.location}</td><td>{m.chair}</td><td><span className={'badge '+(m.status==='Draft'?'pending':'')}>{m.status}</span></td><td><button className="btn secondary" onClick={()=>onEdit(m)}>Edit</button>{' '}<button className="btn secondary" onClick={()=>onExport(m)}>Export</button></td></tr>)}</tbody></table></div>}
